# Generated by Django 5.0.2 on 2025-03-05 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BibleCharadesQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('scripture', models.CharField(max_length=100)),
                ('difficulty', models.CharField(max_length=20)),
                ('image_url', models.URLField()),
                ('options', models.JSONField()),
                ('correct_answer', models.CharField(max_length=200)),
                ('game_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bible_charades_questions', to='games.gametype')),
            ],
            options={
                'ordering': ['?'],
            },
        ),
        migrations.CreateModel(
            name='FindTheBibleVerseQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('book', models.CharField(max_length=50)),
                ('chapter', models.IntegerField()),
                ('verse', models.IntegerField()),
                ('options', models.JSONField()),
                ('correct_answer', models.CharField(max_length=100)),
                ('game_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='find_the_bible_verse_questions', to='games.gametype')),
            ],
            options={
                'ordering': ['?'],
            },
        ),
        migrations.CreateModel(
            name='ScriptureSprintQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verse', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('pack_type', models.CharField(max_length=50)),
                ('versions', models.JSONField()),
                ('game_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scripture_sprint_questions', to='games.gametype')),
            ],
            options={
                'ordering': ['?'],
            },
        ),
    ]
