# Generated by Django 5.0.2 on 2025-03-05 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_biblecharadesquestion_findthebibleversequestion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scripturesprintquestion',
            name='versions',
        ),
        migrations.CreateModel(
            name='VerseVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation', models.CharField(max_length=10)),
                ('text', models.TextField()),
                ('verse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='games.scripturesprintquestion')),
            ],
            options={
                'unique_together': {('verse', 'translation')},
            },
        ),
    ]
